apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: lockvalidation-cfg 
  labels:
    app: lockvalidation 
webhooks:
  - name: lockvalidation.kotas.tech 
    clientConfig:
      service:
        name: lockvalidation-svc
        namespace: default
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQyRENDQXNDZ0F3SUJBZ0lVUzhobWFRWUIrOHc5cHh4TTVwbUJuTy96Um1nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUtiV2x1YVd0MVltVkRRVEFlRncweE9UQTVNVEV4TURFM01EQmFGdzB5TURBNQpNVEF4TURFM01EQmFNQ2t4SnpBbEJnTlZCQU1USG14dlkydDJZV3hwWkdGMGFXOXVMWE4yWXk1a1pXWmhkV3gwCkxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLd0xscm44Y3VmbDZWN2EKN2M5emVVdTVva2RkVGhITm9WTGc1aWNDWUUzS1FXMXZINnF6dzJvcU5qM0F5eURCODJKc0t5a3kvVjRZRzRiLworaGx1WDdZWGNEY3lOWklZZUJBYzA0RlI1S3pnNDhOb2UzNGJoNjJXckFLQzZXWWxaMHlQYkxsTzA3UzdiaUxTCjNZT0xnNTRjQTFXQVVyaFZRdjVXcUw3SWJOblpLb0VZMlRkdDdXdURkMVpLR1FuREcrMjdyZzhONXBtRitlV3YKN3lwSDN1WEF6T0krclhvQWwvbkJJcm0yZ0oxNTJCUEttRmgvOTNHdzdqUmM3Nktic3F3Smt4YUJYRDQ1MmRncwo5TC9CUFJoSmtKRGxHKzF0c3dxTCtTSnhUdFZ2U2JKOVhhelNSd1YrWEUvZ2dtU2Y4WVFqMEZHMWRLWDNYVS9tCk5kMjVkM2NDQXdFQUFhT0NBUW93Z2dFR01BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3IKQmdFRkJRY0RBVEFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUWhrYVpCcm1MSm5pUG5pNStFN21mSgpTNVh6UFRDQnNRWURWUjBSQklHcE1JR21naEpzYjJOcmRtRnNhV1JoZEdsdmJpMXpkbU9DR214dlkydDJZV3hwClpHRjBhVzl1TFhOMll5NWtaV1poZFd4MGdoNXNiMk5yZG1Gc2FXUmhkR2x2YmkxemRtTXVaR1ZtWVhWc2RDNXoKZG1PQ0pteHZZMnQyWVd4cFpHRjBhVzl1TFhOMll5NWtaV1poZFd4MExuTjJZeTVqYkhWemRHVnlnaXhzYjJOcgpkbUZzYVdSaGRHbHZiaTF6ZG1NdVpHVm1ZWFZzZEM1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFicmRFTWhlVnBtcW5tTURUVGJiekxpQ3hxS1RNRzVZRTBmdDljV0FzbHZYNktRWjYKdWM3U0p5eWp3SlREeU9Pc2c4cU40VkNBTnQ4My90bkJyclQ4T2MzMU9vRjhQNStCejl0cVVqWjlMalFvSE5QVQpmVGh3LzJla0FlZ3R3NGxOY2tlYmloSlk0K1hlSlFDcURkUC9kTHNkbURNT29uODhIZ2labWNHbXBXRkhxU2V2CnR5QkxjTTJWMSt4MjVtTXR3aEhJYzYxcXZBRUhjYVBpS0VSclgyR2pFQTF3SElGdmZuSnhUcFBEaWhJR1ljRWEKWW1YNE5HVDBGM3VsUXNTZUF1cGRkOGxlR2NvdjZpcE94Q0JKbWVpWklVbEVmc1plMzNGRzRYbGM0ODc3ZVBCVwo2YXgyRGp2K3FXdk8wRjJQZTBFNUloVlFqQ0JKQzMxNFY4MVBYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: 
          - CREATE
          - UPDATE
          - DELETE
          - CONNECT
        apiGroups:
          - "*"
        apiVersions: 
          - "*"
        resources: 
          - "*"
    namespaceSelector:
      matchLabels:
        lockable: "true"
