trigger: 
  branches:
    include:
      - master
pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.13.5'
    goPath: '%Agent.BuildDirectory/go'
- script: |
    make get-dependencies
  displayName: Download module dependencies
- script: |
    echo "gopath"
    echo $GOPATH
    make gen-code
    make build-code
  displayName: Build project
- script: |
    make test-unit
  displayName: Unit test
