trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'


steps:
  - script: |
      SECRET=$(DOCKER-CLI)
      docker login -u pkotas --password-stdin <<< $SECRET 
    displayName: Docker login
  - script: |
      docker pull pkotas/k8s-object-lock:"$TAG"
    displayName: Pull image

