trigger: none
pr: none

parameters:
  - name: version
    displayName: Config version
    type: string
    default: ''

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - script: |
      echo "and we end"
      exit 1
  - ${{ ne(parameters.version, 'latest') }}:
    - checkout: git://k8s-object-lock/k8s-config@refs/tags/${{ parameters.version }}
  - ${{ eq(parameters.version, 'latest') }}:    
    - checkout: git://k8s-object-lock/k8s-config@refs/heads/master
  - script: |
      cd $(Agent.BuildDirectory)/s/k8s-config
      less config.yaml
  - script: |
      SECRET=$(DOCKER-CLI)
      docker login -u pkotas --password-stdin <<< $SECRET 
    displayName: Docker login
  - script: |
      docker pull pkotas/k8s-object-lock:"$TAG"
    displayName: Pull image

