trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: k8s-config
      type: git
      endpoint: petr
      name: k8s-config/k8s-config

steps:
  - checkout: self
  - checkout: k8s-config
  - script: |
      cd $(Agent.BuildDirectory)/s/k8s-config
      less config.yaml
      export VAR="test"
      echo "##vso[task.setvariable variable=VAR]$VAR"
  - script: |
      SECRET=$(DOCKER-CLI)
      docker login -u pkotas --password-stdin <<< $SECRET 
    displayName: Docker login
  - script: |
      echo "$VAR"
      docker pull pkotas/k8s-object-lock:"$TAG"
      CONTAINER=$(docker create pkotas/k8s-object-lock:"$TAG")
      docker cp $CONTAINER:/usr/app/lockvalidation lockvalidation
      stat lockvalidation
    displayName: Pull image

