trigger: none
pr: none

parameters:
  - name: version
    displayName: Config version
    type: string

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - checkout: git://k8s-object-lock/k8s-config@refs/tags/${{ parameters.version }}
  - script: |
      cd $(Agent.BuildDirectory)/s/k8s-config
      less config.yaml

