trigger: none


pool:
  vmImage: 'ubuntu-latest'

steps: 
 - task: GoTool@0
   inputs:
     version: '1.13.5'
 - task: Go@0
   inputs:
     command: 'get'
     arguments: '-d'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
