trigger: 
  branches:
    include:
      - master
      # - refs/tags/*
    # exclude:
      # - master
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- script: |
    make get-dependencies
  displayName: Download module dependencies
- script: |
    export GOPATH=$(go env GOPATH)
    env
    make build
  displayName: Compile the code using makefile
- script: |
    MESSAGE=$(git for-each-ref refs/tags/$(Build.SourceBranch))
    echo "$MESSAGE" > release.txt
- task: GithubRelease@0
  displayName: Publish release notes
  inputs:
    githubConnection: k8s-object-lock
    repositoryName: petrkotas/k8s-object-lock
    action: create
    releaseNotesFile: $(System.DefaultWorkingDirectory)/**/release.txt
    addChangeLog: true

