trigger: 
  branches:
    include:
      - master
      # - refs/tags/*
    # exclude:
      # - master
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- script: |
    make get-dependencies
  displayName: Download module dependencies
- script: |
    env
    make build
  displayName: Compile the code using makefile

