trigger: none
pr: none

schedules:
- cron: "*/2 * * * *"
  displayName: Every fifth minute do some stuff
  always: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "Read variable - $(SECRET)"
  displayName: "Test"