trigger: none
pr: none

resources:
  pipelines:
  - pipeline: e2e
    source: petrkotas.k8s-object-lock.code-check
    trigger: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
      version: '1.13.5'
      goPath: '/home/vsts/work/go'
- script: |
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
    
    go get sigs.k8s.io/kind

    make get-dependencies
  displayName: Prepare e2e runtime
- script: |
    make deploy-cluster
    make deploy-base
    make gen-cert
    make gen-code
    make build-code
    make build-docker
    make cluster-load-image
    make deploy-for-dpl
  displayName: Prepare build 
- script: |
    make test-e2e
  displayName: Run e2e